image:
  file: .gitpod.Dockerfile

tasks:
  - command: curl -sL https://raw.githubusercontent.com/twtwtw-gj/rewrite-git-user-data-bash/main/index.sh | bash
  - command: git clone https://github.com/simonmar/parconc-examples; cd parconc-examples
